#!/bin/sh
free_mem=`free -m | awk 'NR==2{print $NF}'`
if [ $free_mem -lt 3600 ]
then
    echo "内存不足，当前是$free_mem" | tee /tmp/mem.log
    mail -s "$(date) 内存报警" 1111111@qq.com < /tmp/mem.log
else
    echo "内存充足."
fi
